name: Run Tests

on:
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: "--max-old-space-size=4096"

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18'

            #- name: Install dependencies
            #  run: npm install

            #- name: Upload generated file
            #  uses: actions/upload-artifact@v4
            #  with:
            #    name: package-lock
            #    path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Lint code
              run: npm run lint-fix

            - name: Build project
              run: npm run build

            - name: Upload project files
              uses: actions/upload-artifact@v4
              with:
                name: next
                path: .next
